### ISSUE TITLE
/api/data returns a empty array and data sources under map is not loading

### ISSUE THREAD

**Issue by dehemi-weerakkody** [openaddresses/batch#446]
**Describe the bug**
/api/data returns a empty array, and in the site https://batch.openaddresses.io/data#map=0/0/0 shows under map "no data sources" or just empty

**To Reproduce**
1. Go to [home page](https://batch.openaddresses.io/data#map=0/0/0)
3. Scroll down to under map
4. See "no data sources" or just empty

**Expected behavior**
Should show the address lists

**Screenshots**

![Image](https://github.com/user-attachments/assets/c42a3de1-6157-4301-83b9-9702f97c2391)

![Image](https://github.com/user-attachments/assets/c8d7df3d-d708-4d42-80ff-e83673ca0b9b)

**Comment by iandees** [comment]
This was fixed in #445. Can you try reloading the page please?

**Comment by dehemi-weerakkody** [comment]
@iandees I tried reloading with disabled cache on my browser, the issue is still there

**Comment by iandees** [comment]
If you have `curl` on your system, can you run `curl -v https://batch.openaddresses.io/api/data > /dev/null` and paste the output here?

**Comment by dehemi-weerakkody** [comment]
Here, But It's now back to working. But, I now can't login to the platform. and can't download address lists. Should I open another issue for that

![Image](https://github.com/user-attachments/assets/f81cd6f8-0ce6-44ba-b67a-255419f9f2bf)

Here's the output that you as asked for

```$ curl -v https://batch.openaddresses.io/api/data > /dev/null
* Host batch.openaddresses.io:443 was resolved.
* IPv6: (none)
* IPv4: 172.67.136.189, 104.21.70.146
*   Trying 172.67.136.189:443...
* schannel: disabled automatic use of client certificate
* Connected to batch.openaddresses.io (172.67.136.189) port 443
* using HTTP/1.x
> GET /api/data HTTP/1.1
> Host: batch.openaddresses.io
> User-Agent: curl/8.11.0
> Accept: */*
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 200 OK
< Date: Mon, 17 Mar 2025 15:16:37 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cf-Ray: 921d73d569083f74-SIN
< Server: cloudflare
< Vary: Origin
< Access-Control-Allow-Credentials: true
< Etag: W/"eb036-YZmzWrvcE4NX4s9xhB8n5hr8yUY"
< Cache-Control: max-age=432000
< Cf-Cache-Status: HIT
< Age: 35
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=9%2B8CezAIUyoq8WwwGvqeRN%2BUwCLtyUrWmSo%2F5JuMRHWAs2y7LWDNPtqabvKF8yYO7jz7w3MfDouUyEfF7klNnKURYqmkh9Qd1eKffap647zeRRyzSVCoYE7hck1Xns8FYe05mixdMBSY"}],"group":"cf-nel","max_age":604800}
< Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< alt-svc: h3=":443"; ma=86400
< server-timing: cfL4;desc="?proto=TCP&rtt=148926&min_rtt=148303&rtt_var=56860&sent=5&recv=6&lost=0&retrans=0&sent_bytes=3128&recv_bytes=654&delivery_rate=27125&cwnd=251&unsent_bytes=0&cid=e39cb683b02f6a32&ts=226&x=0"
<
* Connection #0 to host batch.openaddresses.io left intact```

**Comment by iandees** [comment]
Are you still having problems?

**Comment by dehemi-weerakkody** [comment]
Yeah, I still get this error. 

![Image](https://github.com/user-attachments/assets/7ba0fc91-7f11-42f8-918c-f75118bca0ae)

and also when I call `https://batch.openaddresses.io/api/job/561512/output/source.geojson.gz` I get status `502` with cloudflare message 

`<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>batch.openaddresses.io | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Bad gateway</span>
              <span class="code-label">Error code 502</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=batch.openaddresses.io" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">20[25](https://github.com/Briggs-Walker/briggs-automated-address-pipeline/actions/runs/13964551341/job/39091932544#step:4:26)-03-20 08:04:25 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>
<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-[40](https://github.com/Briggs-Walker/briggs-automated-address-pipeline/actions/runs/13964551341/job/39091932544#step:4:41)0 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=batch.openaddresses.io" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">San Jose</span>`

**Comment by iandees** [comment]
I cleared the cache again. Please try again.

**Comment by dehemi-weerakkody** [comment]
Still the same issue. code 503 when I try to login,  502 for  `https://batch.openaddresses.io/api/job/561512/output/source.geojson.gz`

**Comment by iandees** [comment]
All of this is working for me, so I'm very confused. Do you have some kind of proxy or local cache setup somewhere on your network? Do you see the same thing from your phone while on cell service or other computer?

**Comment by iandees** [comment]
Closing this. Please reopen if you're seeing problems.
